version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: website-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<YourStrong@Passw0rd>
